### ISSUE TITLE
Stuck at CDS Prediction

### ISSUE THREAD

**Issue by limpengken** [pedronachtigall/CodAn#10]
Hi, CodAn always stuck at the CDS prediction step. Can you help me? I made sure that my python version = 3.7 and the lines of my fasta file did not exceed 1.2k characters. I installed Codan using conda in a new environment following the tutorial.

This is the command I used:

codan.py -t ./CodAn_output/good.Psilotum_nudum_transcripts_90.fasta -c 3 -m ./CodAn_models/PLANTS_partial/ -s plus

I am stuck here:

2021-09-23 16:41:06 >>>> starting CodAn (v1.1 June 2021)...
        transcript file -> ./CodAn_output/good.Psilotum_nudum_transcripts_90.fasta
        model -> ./CodAn_models/PLANTS_partial/
        strand prediction -> plus
        number of threads -> 3
2021-09-23 16:41:06 >>>> CDS prediction...

**Comment by pedronachtigall** [comment]
Hi @limpengken ,

Sorry for the slow response.
Did you solve this issue?
If not, try to specify the entire PATH to the model or the PATH from the working directory to the model (i.e., remove the "./" from model PATH). Do this to the transcript file also.

Hope that this helps you, please let me know if are still having issues.

Best,
Pedro

**Comment by wook2014** [comment]
I meet up with problems similar to @limpengken. I have some denovo transcript from trinity result. when I tried to find cds from original fasta file, it stuck for a longtime. My python version is 3.12.8 and I installed codan in a new conda environment.
I used the command
```
codan.py  -c 80 -s plus -t COC-test.fa -o COC-test -m /data/wook/proteomics/trans/codan/VERT_full/
```
I noticed in Q4 that the header should not include " " and ":" and "|". So I replaced them and make sure all character in header are legal, but it is still very slow. 
the palce where got stuck is:
```
2025-01-14 16:05:07 >>>> starting CodAn (v1.1 June 2021)...
        transcript file -> COC-test.fa
        model -> /data/wook/proteomics/trans/codan/VERT_full/
        strand prediction -> plus
        number of threads -> 80
2025-01-14 16:05:07 >>>> CDS prediction...
```
similar with @limpengken and After that I used first 1000 seqs for test and I got an error:
```
Traceback (most recent call last):
  File "/home/wook/miniforge3/envs/codan/bin/codan.py", line 510, in <module>
    __main__()
  File "/home/wook/miniforge3/envs/codan/bin/codan.py", line 488, in __main__
    _codan_PLUS_(options.transcripts, options.output_folder, options.model, options.cpu)
  File "/home/wook/miniforge3/envs/codan/bin/codan.py", line 339, in _codan_PLUS_
    _retrieveORF_PLUS_(transcripts, outF)
  File "/home/wook/miniforge3/envs/codan/bin/codan.py", line 106, in _retrieveORF_PLUS_
    os.remove(transcripts+".index")
FileNotFoundError: [Errno 2] No such file or directory: 'COC-test.fa.index'
```
but there is COC-test.fa.index.pag and COC-test.fa.index.dir file found. There is no problem that the program not to delete the index file but it is confused that the program stuck for such a long time (over 10 hours) with one fasta file about 130M size.

**Comment by edgardomortiz** [comment]
Hi @pedronachtigall 
I have exactly the same issue, the program gets stuck at "CDS prediction..."

However it depends on the computer, in my personal laptop (a Mac) it runs correctly as well as in a Linux workstation. However when we submit jobs to the university HPC it gets forever on the CDS prediction step

I have used full paths for all the arguments, downgraded python to 3.7, but I can't get CodAn to run in the HPC

Edgardo

**Comment by edgardomortiz** [comment]
Hi Pedro,

I solved the problem by reinstalling CodAn as follows:

```
mamba create -n codan -c bioconda -c conda-forge codan python=3.7 biopython perl perl-bioperl perl-mce blast
```

The issue arises when one uses the recommended bioconda installation command:

```
mamba create -n codan -c bioconda codan
```

Perhaps some versions of some packages are not found in `bioconda` and it needs to search also `conda-forge`
Thanks for developing CodAn! very useful

Edgardo

**Comment by pedronachtigall** [comment]
Hi Edgardo,

Glad to know that it is working and that CodAn is useful. Thanks for debugging it.
It is being a long time since I developed the conda recipe. I may need to run a fest tests and update it properly to avoid such issues. I will try to do it within the next weeks.

Best,
Pedro
