### ISSUE TITLE
remove file error.

### ISSUE THREAD

**Issue by xiekunwhy** [pedronachtigall/CodAn#11]
Hi,

Why you remove file without checking existences?
grep -n os.remove codan.py
106:    os.remove(transcripts+".index")
140:    os.remove(outF+"minus.fa")
141:    os.remove(outF+"minus.fa.index")
287:    os.remove(outF+"ORFs_plus.gtf")
288:    os.remove(outF+"ORFs_minus.gtf")
289:    os.remove(outF+"minus.fa")
290:    os.remove(outF+"minus.fa.index")
291:    os.remove(transcripts+".index")
All of these may cause error like following when the output directory is empty(or run codan first time).
Traceback (most recent call last):
  File "/Bio/User/kxie/pipeline/geneAnnot/bin/codan/bin/codan.py", line 524, in <module>
    __main__()
  File "/Bio/User/kxie/pipeline/geneAnnot/bin/codan/bin/codan.py", line 506, in __main__
    _codan_BOTH_(options.transcripts, options.output_folder, options.model, options.cpu)
  File "/Bio/User/kxie/pipeline/geneAnnot/bin/codan/bin/codan.py", line 355, in _codan_BOTH_
    _retrieveORF_BOTH_(transcripts, outF+"minus.fa", outF)
  File "/Bio/User/kxie/pipeline/geneAnnot/bin/codan/bin/codan.py", line 290, in _retrieveORF_BOTH_
    os.remove(outF+"minus.fa.index")
FileNotFoundError: [Errno 2] No such file or directory: './02.ccs/codan/minus.fa.index'
Would you please disable the removings or check existences first?

Best,
Kun

**Comment by xiekunwhy** [comment]
Sorry, I know why now.
